"""Parâmetros calibráveis do GuaritaDigital."""

QUADROS_ANTES = 3
QUADROS_DEPOIS = 3
MELHORES_QUADROS = 4

NITIDEZ_MINIMA = 45.0
BRILHO_MINIMO = 35.0
BRILHO_MAXIMO = 225.0
CONTRASTE_MINIMO = 18.0
ALTURA_MINIMA_PLACA = 32

CONFIANCA_YOLO_MINIMA = 0.28
CONFIANCA_OCR_MINIMA = 0.45
CONFIANCA_OCR_CORRIGIDA = 0.62
QUADROS_PARA_CONFIRMAR = 2
MARGEM_EMPATE = 0.10
INTERVALO_DUPLICIDADE_SEGUNDOS = 20.0

SALVAR_DIAGNOSTICO = True
PASTA_DIAGNOSTICO = "diagnosticos"

REPOSITORIO_MODELO = "yasirfaizahmed/license-plate-object-detection"
ARQUIVO_MODELO = "best.pt"
